const GITHUB_API = 'https://api.github.com';
const DATA_PATH = 'users';

function originFor(env) { return String(env.APP_ORIGIN || '').replace(/\/$/, ''); }
function allowedOrigin(request, env) { const origin = request.headers.get('Origin') || ''; return origin === originFor(env) ? origin : originFor(env); }
function headers(request, env, extra = {}) { return {'Access-Control-Allow-Origin': allowedOrigin(request, env), 'Access-Control-Allow-Credentials':'true', 'Vary':'Origin', ...extra}; }
function json(request, env, body, status = 200) { return new Response(JSON.stringify(body), {status, headers:headers(request, env, {'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'})}); }
function redirect(url, request, env, cookies=[]) { const responseHeaders=new Headers(headers(request,env,{'Location':url})); for(const value of (Array.isArray(cookies)?cookies:[cookies])) responseHeaders.append('Set-Cookie',value); return new Response(null,{status:302,headers:responseHeaders}); }
function randomToken(bytes=24) { const data=new Uint8Array(bytes); crypto.getRandomValues(data); return btoa(String.fromCharCode(...data)).replaceAll('+','-').replaceAll('/','_').replaceAll('=',''); }
function bytesToBase64(bytes) { return btoa(String.fromCharCode(...bytes)); }
function base64ToBytes(value) { return Uint8Array.from(atob(value), char=>char.charCodeAt(0)); }
function encodeUtf8Base64(value) { return bytesToBase64(new TextEncoder().encode(value)); }
function decodeUtf8Base64(value) { return new TextDecoder().decode(base64ToBytes(value)); }
async function sessionKey(secret) { const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(secret)); return crypto.subtle.importKey('raw',digest,{name:'AES-GCM'},false,['encrypt','decrypt']); }
async function seal(value, secret) { const iv=crypto.getRandomValues(new Uint8Array(12)); const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},await sessionKey(secret),new TextEncoder().encode(JSON.stringify(value))); return `${bytesToBase64(iv)}.${bytesToBase64(new Uint8Array(encrypted))}`; }
async function unseal(value, secret) { try { const [iv,body]=String(value||'').split('.'); if(!iv||!body)return null; const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:base64ToBytes(iv)},await sessionKey(secret),base64ToBytes(body)); return JSON.parse(new TextDecoder().decode(plain)); } catch { return null; } }
function cookieValue(request, name) { const cookies=request.headers.get('Cookie')||''; return cookies.split(';').map(v=>v.trim()).find(v=>v.startsWith(`${name}=`))?.slice(name.length+1) || ''; }
function cookie(name, value, maxAge) { return `${name}=${value}; Max-Age=${maxAge}; Path=/; HttpOnly; Secure; SameSite=Lax`; }
async function session(request, env) { const value=await unseal(cookieValue(request,'talentisos_session'),env.SESSION_SECRET); return value?.exp>Date.now()?value:null; }
function githubHeaders(token) { return {'Accept':'application/vnd.github+json','Authorization':`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28','User-Agent':'TalentisOS-X-sync'}; }
async function github(request, token, path, options={}) { return fetch(`${GITHUB_API}${path}`,{...options,headers:{...githubHeaders(token),...(options.headers||{})}}); }
async function oauthLogin(request, env) { const state=randomToken(); const redirectUri=`${new URL(request.url).origin}/auth/callback`; const params=new URLSearchParams({client_id:env.GITHUB_CLIENT_ID,redirect_uri:redirectUri,scope:'repo',state}); return redirect(`https://github.com/login/oauth/authorize?${params}`,request,env,cookie('talentisos_oauth_state',state,600)); }
async function oauthCallback(request, env) { const url=new URL(request.url); const state=url.searchParams.get('state')||''; if(!state||state!==cookieValue(request,'talentisos_oauth_state'))return json(request,env,{error:'Invalid OAuth state'},400); const code=url.searchParams.get('code'); if(!code)return json(request,env,{error:'GitHub did not return an authorization code'},400); const tokenResponse=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{'Accept':'application/json','Content-Type':'application/json'},body:JSON.stringify({client_id:env.GITHUB_CLIENT_ID,client_secret:env.GITHUB_CLIENT_SECRET,code,redirect_uri:`${new URL(request.url).origin}/auth/callback`})}); const tokenBody=await tokenResponse.json(); if(!tokenBody.access_token)return json(request,env,{error:'GitHub authorization failed'},502); const userResponse=await github(request,tokenBody.access_token,'/user'); if(!userResponse.ok)return json(request,env,{error:'Could not read GitHub profile'},502); const user=await userResponse.json(); const sealed=await seal({token:tokenBody.access_token,id:user.id,login:user.login,exp:Date.now()+7*24*60*60*1000},env.SESSION_SECRET); return redirect(`${originFor(env)}/?github=connected`,request,env,`${cookie('talentisos_session',sealed,7*24*60*60)}; ${cookie('talentisos_oauth_state','',0)}`); }
async function getData(request, env, auth) { const path=`/repos/${env.GITHUB_DATA_REPO}/contents/${DATA_PATH}/${auth.id}.json`; const response=await github(request,auth.token,path); if(response.status===404)return json(request,env,{data:null}); if(!response.ok)return json(request,env,{error:'Could not read workspace data'},502); const body=await response.json(); const decoded=decodeUtf8Base64(String(body.content||'').replaceAll('\n','')); return json(request,env,{data:JSON.parse(decoded),sha:body.sha}); }
async function putData(request, env, auth) { const incoming=await request.json(); const content=encodeUtf8Base64(JSON.stringify(incoming)); const path=`/repos/${env.GITHUB_DATA_REPO}/contents/${DATA_PATH}/${auth.id}.json`; const existing=await github(request,auth.token,path); const current=existing.ok?await existing.json():null; const response=await github(request,auth.token,path,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`Update TalentisOS workspace for ${auth.login}`,content,sha:current?.sha})}); if(!response.ok)return json(request,env,{error:'Could not save workspace data to GitHub'},502); return json(request,env,{saved:true}); }
export default {async fetch(request,env) { try { if(request.method==='OPTIONS')return new Response(null,{status:204,headers:headers(request,env,{'Access-Control-Allow-Methods':'GET,PUT,OPTIONS','Access-Control-Allow-Headers':'Content-Type'})}); const url=new URL(request.url); if(url.pathname==='/auth/login')return oauthLogin(request,env); if(url.pathname==='/auth/callback')return oauthCallback(request,env); if(url.pathname==='/auth/logout')return redirect(`${originFor(env)}/`,request,env,cookie('talentisos_session','',0)); if(url.pathname==='/api/me'){const auth=await session(request,env);return json(request,env,{authenticated:!!auth,user:auth?{id:auth.id,login:auth.login}:null})} const auth=await session(request,env); if(!auth)return json(request,env,{error:'Authentication required'},401); if(url.pathname==='/api/data'&&request.method==='GET')return getData(request,env,auth); if(url.pathname==='/api/data'&&request.method==='PUT')return putData(request,env,auth); return json(request,env,{error:'Not found'},404); } catch(error) { console.error(JSON.stringify({message:error?.message||'Worker error'})); return json(request,env,{error:'Internal server error'},500); } }};
